apiVersion: apps/v1
kind: Deployment
metadata:
 name: todoapp-deployment
 namespace: bootcampgp2
spec:
 replicas: 2
 selector:
   matchLabels:
     app: todoapp
 template:
   metadata:
     labels:
       app: todoapp
   spec:
     containers:
       - name: to-do-app
         image: ppilco/to-do-app:1.0.0
         ports:
           - containerPort: 3000