name: todo-ci-action

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
on:
  push:
    branches: [ "bootcamp" ]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/to-do-app:3.0.0

    steps:
      - uses: actions/checkout@v2
      - name: saharshMMC AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          command: |
            kubectl apply -f ./deployment.yaml
